---
title: "Acedemic Project"
author: "Ruiqi Yan (ry2417)"
date: "1/5/2022"
output: html_document
---

# Academic Projects

## Simulation Study: Comparison between K-means and LCA Clustering 

Based on the algorithm of Monte Carlo simulation, build some functions in R programming to simulate data with specific features of interest. Applied data visualization to check whether the simulated data have desired features. Set different simulation scenarios and simulate data 100 times for each scenario. Applied two clustering methods and compare their performance using quantitative analysis in R programming. Visualized the simulation results and the performance results to demonstrate the comparison. Made some practical recommendations about the selection of clustering method in different scenario and present the analysis and results in a 15-minutes presentation.

## Exploratory Analysis About Drug Use Among Youth                		
*Fall 2021*\
This project used the data collected by surveys of Youth Risk Behavior Surveillance System and explored the association between drug use and risky behaviors among high school students by R programming. Applied data visualization and interactive plots to do exploratory data analysis. Demonstrate the overall drug use trends among youth over each state, gender and races. Constructed functions in R to do hypothesis testing about the correlation between drug use status and risky behavior and estimate the magnitude of the correlation. Built a website through GitHub called [Risky Drug](https://meanstudent.github.io/DS_FinalProject.io/) to show analysis results and the interactive plots.

## Model Fitting for Crime Rate and Demographic Characteristics Variables
*Fall 2021*\
This project was building a multivariate regression model to predict the crime rate though demographic features using R programming. Drew pair-wise plots to select variables and interaction terms. Applied automatic stepwise procedures with various criteria to get several candidate models. The utilized cross-validation to select the model with lowest prediction error as the final model. Checked the violation of assumptions using quantitative analysis and visualization. Generated a report by R.

## Causal Inference of Bike-Sharing Usage
*Spring 2019*\
This project was manipulated on R programming and used two data sets, bike-sharing and weather in Seattle, to infer a multivariate regression model that shows the causal effects of weather on the frequency and time length of bike-sharing. Cleaned and merged two data sets. Used stepwise criteria and statistical analysis to select variables. Fitted multivariate regression model using three different types of models. Checked the performance of these models and selected the final model based on the performance. Present analysis results and the final model on a post fair.

## [RecipEZ](https://chunmochen.shinyapps.io/Info201-Final_Project/)
*Spring 2019*\
Designed and constructed a website that users can search for the recipes that fit their nutrition and budget limitation through Shiny. The nutrition and recipe data were absorbed from other website by API. Given all the option of nutrition for users to narrow down their choice of recipes.

## The Association Between Marital Status and Demographic Characteristic	
*Spring 2018*\
This project was a cross-sectional study that analyzed data obtained from UCI Machine Learning to find the association between marital status and demographic characteristics. Cleaned data and determine the demographic variables of interest. Summarized data and describe the characteristics of each variable of interest. Test the correlation between marital status versus age, education, income, and gender. Interpreted the result and made some conclusions about the rationality of the result. Discussed limitations and the possibility of project expansion.

## Brain Analysis Final Project STAT 498	
*Spring 2018*\
This project was initiated from a companion paper that used the Bayesian method to explore a brain misunderstanding. Designed a comparable questionnaire and collected responses from students at the University of Washington. Entered, cleaned and analyzed new data set by methods from companion paper. Generated a report that compares results in the companion paper and results of the new data set. Discussed validity of the previous methods and the availability of new methods. Used data visualization to demonstrate conclusions in class.\

